### ISSUE TITLE
[Feature Request] Add support for Prezi view urls

### ISSUE THREAD

**Issue by zanyjokester** [Gertje823/prezi2pdf#2]
Hi there!
I keep getting this total = len(data['frames']) error. I would really appreciate some support! Thank you 👍

**Comment by Gertje823** [comment]
Could you please provide the exact error and the url you are trying to download?

**Comment by zanyjokester** [comment]
Traceback (most recent call last):
  File "/Users/zanyjokester/prezi2pdf.py", line 66, in <module>
    download_presentation(id)
  File "/Users/zanyjokester/prezi2pdf.py", line 45, in download_presentation
    total = len(data['frames'])
                ~~~~^^^^^^^^^^
KeyError: 'frames'



https://prezi.com/view/O9p57Tbkn0RS6YpBY5f4/

**Comment by Gertje823** [comment]
Currently Prezi view urls are not supported. They are rendered by the client as you open the page.
So there is no pre rendered image available.

The currently supported urls are:
Prezi Video:  `prezi.com/v/` 
Prezie Presentation: `prezi.com/p/`

**Comment by zanyjokester** [comment]
Thank you! I appreciate your response. :)

**Comment by jasp-nerd** [comment]
The `len(data['frames'])` crash is the same root cause as a couple of other issues here: `/view/` presentations are rendered in the browser, so the API doesn't hand back a frames JSON to count.

If you mainly need the PDF out, I built [unprezi](https://github.com/jasp-nerd/unprezi) for exactly this case. Instead of calling the API, it opens the prezi in a headless browser, steps through the whole path, and screenshots each stop. It handles today's `/view/` links (and older `prezi.com/<id>/` ones) without a paid account.
